# Generated by Django 3.2 on 2022-06-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankprojapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='account_status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
